name: Debug File Structure

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List all files in workspace
      run: ls -R
