name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Navigate to app directory and build
      run: |
        cd android_app
        chmod +x ./gradlew
        ./gradlew assembleDebug

    - name: Upload APK as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: android_app/app/build/outputs/apk/debug/app-debug.apk
